### ISSUE TITLE
Building/Compiling in Raspberry Pi 4

### ISSUE THREAD

**Issue by symbios24** [jonof/jfwhaven#1]
Hello there

Im trying to compile/build the engine in my Raspberry Pi 4 using the latest raspbian buster
I get an error about sdlappricon not found

I have installed all required depends 

Can you tell me the exact way to 
clone/compile/build your engine please??

I cant seem to find any detailed info about.

Any help will be appreciated

Thank you

**Comment by jonof** [comment]
You ought to find it compiles successfully now.

**Comment by actraiser30** [comment]
Is the port fully working by now?
Last time I tried it wasn't working

**Comment by jonof** [comment]
There's an easy way to find out.
